# Generated by Django 3.2.3 on 2021-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
