# Generated by Django 3.2.3 on 2021-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
